<footer class="figarauto-footer">
    <div class="container">
        <div class="row">
            <div class="col col-12">
                <div class="return-top">
                    <a href="#top">Retour haut de page</a>
                </div>
            </div>
        </div>

        <div class="row">
            <section class="footer-section annonceurs col col-4">
                <h2>Annonceurs</h2>
                    <ul>
                        <li><a href="#">Qui sommes-nous ?</a></li>
                        <li><a href="#">Nous contacter</a></li>
                        <li><a href="#">Conditions générales de vente</a></li>
                    </ul>
            </section>

            <section class="footer-section propositions col col-4">
                <h2>Figarauto vous propose</h2>
                <ul>
                    <li><a href="#">Dernières annonces</a></li>
                    <li><a href="#">Annonces par ville</a></li>
                    <li><a href="#">Annonces par département</a></li>
                    <li><a href="#">Annonces par région</a></li>
                </ul>
            </section>

            <section class="footer-section other-links col col-4">
                <h2>Autres liens</h2>
                <ul>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Instagram</a></li>
                </ul>
            </section>
        </div>

        <div class="row">
            <div class="footer-section cookie-settings col col-12">
                <a href="#">Paramétrer les cookies</a>
            </div>
        </div>

        <div class="row">
            <div class="footer-section legal-section col col-12">
                <a href="#">Mentions légales</a>
                <a href="#">Politique de confidentialité</a>
                <a href="#">Politique de cookies</a>
                <a href="#">Fonctionnement du site</a>
            </div>
        </div>

        <div class="row">
            <div class="footer-section copyright col col-12">
                <a href="#">Copyright © 2024 Figarauto</a>
            </div>
        </div>
    </div>
</footer>
