<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="Assets/CSS/style.css">
        <title>Connexion</title>
    </head>
<?php require 'View/navbar.phtml'; ?>
<body>
    <main>
        <h2>Connexion</h2>
            <form action="index.php?controller=auth&action=login" method="post">
                <label for="email">Votre adresse email :</label>
                <input type="email" name="email" id="email" required>
                <label for="password">Votre mot de passe :</label>
                <input type="password" name="password" id="password" required>
                <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['csrf_token'], ENT_QUOTES, 'UTF-8'); ?>">
                <input type="submit" value="Se connecter">
            </form>
        <a href="index.php?controller=auth&action=register">Pas encore de compte? Créer un compte</a>
    </main>
</body>
</html>
<?php require 'View/footer.phtml'; ?>