<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="assets/css/main.css">
        <title>Connexion</title>
    </head>
<?php require 'View/navbar.phtml'; ?>
<body>
    <main class="container">
        <section class="row">
            <div class="col col-12">
                <h2>Connexion</h2>
                <form id="loginForm" method="post" class="col col-6 col-offset-3">
                    <div class="form-group">
                        <label for="email">Votre adresse email :</label>
                        <input type="email" name="email" id="email" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Votre mot de passe :</label>
                        <input type="password" name="password" id="password" required>
                    </div>
                    <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['csrf_token'], ENT_QUOTES, 'UTF-8'); ?>">
                    <div class="form-group">
                        <input type="submit" value="Se connecter">
                    </div>
                </form>
                <div class="col col-12">
                    <a href="index.php?controller=auth&action=register">Pas encore de compte? Créer un compte</a>
                </div>
            </div>
        </section>
    </main>

    <script src="assets/js/login.js"></script>
    <?php require 'View/footer.phtml';?>
</body>
</html>