<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="assets/css/main.css">
        <title>Gestion des utilisateurs</title>
    </head>
<body>
    <main class="container">
        <section class="row">
            <div class="col col-12">
                <h2>Gestion des utilisateurs</h2>
            </div>
            <div class="col col-12">
                <table>
                    <thead>
                        <tr>
                            <th>user_id</th>
                            <th>company_name</th>
                            <th>email</th>
                            <th>siret_number</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users as $user):?>
                            <tr>
                                <td><?php echo $user['user_id'];?></td>
                                <td><?php echo $user['company_name'];?></td>
                                <td><?php echo $user['email'];?></td>
                                <td><?php echo $user['siret_number'];?></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </section>
    </main>
</body>
</html>