<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="Assets/CSS/style.css">
        <title>Gestion des utilisateurs</title>
    </head>
<body>
    <main>
        <h2>Gestion des utilisateurs</h2>
        <table>
            <thead>
                <tr>
                    <th>user_id</th>
                    <th>company_name</th>
                    <th>email</th>
                    <th>siret_number</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user):?>
                    <tr>
                        <td><?php echo $user['user_id'];?></td>
                        <td><?php echo $user['company_name'];?></td>
                        <td><?php echo $user['email'];?></td>
                        <td><?php echo $user['siret_number'];?></td> <!-- si pas de siret c'est que l'uti n'est pas pro -->
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </main>
</body>
</html>