<header class="figarauto-header container">
        <div class="row align-items-center">
            <div class="logo-title-section col col-4">
                <a href="index.php?controller=home&action=home" class="figarauto-logo">
                    <img src="Assets\images\Capture d'écran 2023-09-29 090337.png" alt="Logo de Figarauto">
                </a>
                <h1>Figarauto</h1>
            </div>
            <nav class="figarauto-nav col col-8">
                <ul class="figarauto-menu">
                    <li class="menu-item">
                        <a href="index.php?controller=home&action=home" class="menu-link">Accueil</a>
                    </li>
                    <li class="menu-item">
                        <a href="/annonces/" class="menu-link">Annonces</a>
                    </li>
                    <li class="menu-item">
                        <a href="index.php?controller=user&action=dashboard" class="menu-link">Espace Clients</a>
                    </li>
                    <li class="menu-item">
                        <a href="index.php?controller=annonce&action=create" class="menu-link">Dépôt d'Annonces</a>
                    </li>
                    <li class="menu-item">
                        <a href="/abonnement/" class="menu-link">Abonnement</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="row">
            <div class="search-container col col-12">
                <input type="text" placeholder="Rechercher">
            </div>
        </div>
</header>