<header class="figarauto-header">
        <div class="top-navigation">
            <div class="logo-title-section">
                <a href="index.php?controller=home&action=home" class="figarauto-logo">
                    <img src="Assets\images\Capture d'écran 2023-09-29 090337.png" alt="Logo de Figarauto">
                </a>
                <h1>Figarauto</h1>
            </div>
        </div>
        <nav class="figarauto-nav fixed-top">
            <ul class="figarauto-menu">
                <li class="menu-item">
                    <a href="index.php?controller=home&action=home" class="menu-link">Accueil</a>
                </li>
                <li class="menu-item">
                    <a href="/annonces/" class="menu-link">Annonces</a>
                </li>
                <li class="menu-item">
                    <a href="index.php?controller=user&action=dashboard" class="menu-link">Espace Clients</a>
                </li>
                <li class="menu-item">
                    <a href="index.php?controller=annonce&action=create" class="menu-link">Dépôt d'Annonces</a>
                </li>
                <li class="menu-item">
                    <a href="/abonnement/" class="menu-link">Abonnement</a>
                </li>
            </ul>
        </nav>
        <div class="search-container">
            <div class="search-bar">
                <input type="text" placeholder="rechercher">
            </div>
        </div>
</header>